version: "3.9"

services:
  etl_app:
    build: .
    container_name: etl_orders
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./db:/app/db
      - ./configs:/app/configs
    command: python main.py
